### ISSUE TITLE
Autosubmit supersedes 'equal submissions'

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/obs-autosubmit#1]
Autosubmit has an issue with OBS having two ways to represent the 'current rev' of a package.

Example:
https://build.opensuse.org/request/show/393283 has been superseded by https://build.opensuse.org/request/show/394329

The first submission was based on rev=f9ea...59e, 2nd rev=161

This serves no purpose and only confuses users

**Comment by lnussel** [comment]
https://github.com/openSUSE/osc-plugin-factory/commit/aadd3f96eb910f6acf963b5aba0e2904fe0ab6f2

**Comment by coolo** [comment]
It got even worse as OBS forces the expanded revision on requests.
